### ISSUE TITLE
Where is QUser Class

### ISSUE THREAD

**Issue by hendisantika** [mengjiann/spring-boot-querydsl#1]
Nice article.

I want to ask You something.

Where is QUser Class?

I can't find it. Is it generated when it run?

Thanks

**Comment by mengjiann** [comment]
Thanks! If you look at the pom.xml, there is a plugin which will be activated during the process(maven build lifecycle). The process will scan through all the classes with @Entity annotated and will generate the classes into the target output directory.

```
<plugin>
	<groupId>com.mysema.maven</groupId>
	<artifactId>apt-maven-plugin</artifactId>
	<version>1.1.3</version>
	<executions>
		<execution>
			<goals>
				<goal>process</goal>
			</goals>
			<configuration>
				<outputDirectory>target/generated-sources/java</outputDirectory>
				<processor>com.mysema.query.apt.jpa.JPAAnnotationProcessor</processor>
			</configuration>
		</execution>
	</executions>
</plugin>
```
